#!/usr/bin/env python3
"""
Python CRCL Message Reader

Reads CRCL messages generated by Rust and demonstrates interoperability.
Uses logging to display the parsed messages.
"""

import json
import logging
from pathlib import Path
from typing import List
import sys

# Add crcl_python to path
sys.path.insert(0, str(Path(__file__).parent))

from crcl_python.crclstatus import JointStatusType, JointStatusesType
from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.parsers import JsonParser, XmlParser

# Configure logging with colors and formatting
class ColoredFormatter(logging.Formatter):
    """Custom formatter with colors"""

    COLORS = {
        'DEBUG': '\033[36m',    # Cyan
        'INFO': '\033[32m',     # Green
        'WARNING': '\033[33m',  # Yellow
        'ERROR': '\033[31m',    # Red
        'CRITICAL': '\033[35m', # Magenta
    }
    RESET = '\033[0m'
    BOLD = '\033[1m'

    def format(self, record):
        log_color = self.COLORS.get(record.levelname, self.RESET)
        record.levelname = f"{log_color}{self.BOLD}{record.levelname}{self.RESET}"
        return super().format(record)

# Set up logging
logger = logging.getLogger('CRCL_Reader')
logger.setLevel(logging.DEBUG)

# Console handler with colors
handler = logging.StreamHandler()
handler.setLevel(logging.DEBUG)
formatter = ColoredFormatter(
    '%(levelname)s [%(name)s] %(message)s'
)
handler.setFormatter(formatter)
logger.addHandler(handler)

def read_single_joint_json(filepath: Path):
    """Read a single JointStatusType from JSON"""
    logger.info(f"Reading single joint from: {filepath.name}")

    with open(filepath, 'r') as f:
        data = json.load(f)

    # Manual parsing (simple approach)
    joint = JointStatusType(
        name=data.get('name'),
        joint_number=data.get('joint_number'),
        joint_position=data.get('joint_position'),
        joint_torque_or_force=data.get('joint_torque_or_force'),
        joint_velocity=data.get('joint_velocity')
    )

    logger.info(f"  ✓ Joint: {joint.name}")
    logger.debug(f"    Number: {joint.joint_number}")
    logger.debug(f"    Position: {joint.joint_position}°")
    logger.debug(f"    Torque: {joint.joint_torque_or_force} Nm")
    logger.debug(f"    Velocity: {joint.joint_velocity}°/s")

    return joint

def read_multiple_joints_json(filepath: Path):
    """Read JointStatusesType from JSON"""
    logger.info(f"Reading multiple joints from: {filepath.name}")

    with open(filepath, 'r') as f:
        data = json.load(f)

    # Parse the joints
    joint_statuses = []
    for j_data in data.get('joint_status', []):
        joint = JointStatusType(
            name=j_data.get('name'),
            joint_number=j_data.get('joint_number'),
            joint_position=j_data.get('joint_position'),
            joint_torque_or_force=j_data.get('joint_torque_or_force'),
            joint_velocity=j_data.get('joint_velocity')
        )
        joint_statuses.append(joint)

    joints_msg = JointStatusesType(
        name=data.get('name'),
        joint_status=joint_statuses
    )

    logger.info(f"  ✓ Message: {joints_msg.name}")
    logger.info(f"  ✓ Found {len(joints_msg.joint_status)} joints:")

    for joint in joints_msg.joint_status:
        logger.debug(f"    • {joint.name}: pos={joint.joint_position:.2f}, vel={joint.joint_velocity:.2f}")

    return joints_msg

def read_trajectory_sequence(filepath: Path):
    """Read a sequence of joint states (trajectory)"""
    logger.info(f"Reading trajectory sequence from: {filepath.name}")

    with open(filepath, 'r') as f:
        data_list = json.load(f)

    logger.info(f"  ✓ Found {len(data_list)} trajectory points")

    trajectory = []
    for i, data in enumerate(data_list):
        joint_statuses = []
        for j_data in data.get('joint_status', []):
            joint = JointStatusType(
                name=j_data.get('name'),
                joint_number=j_data.get('joint_number'),
                joint_position=j_data.get('joint_position'),
                joint_torque_or_force=j_data.get('joint_torque_or_force'),
                joint_velocity=j_data.get('joint_velocity')
            )
            joint_statuses.append(joint)

        joints_msg = JointStatusesType(
            name=data.get('name'),
            joint_status=joint_statuses
        )
        trajectory.append(joints_msg)

        logger.debug(f"    Point {i}: {joints_msg.name}")
        for joint in joints_msg.joint_status:
            logger.debug(f"      {joint.name}: pos={joint.joint_position:.3f}")

    return trajectory

def read_xml_message(filepath: Path):
    """Read CRCL message from XML using xsdata"""
    logger.info(f"Reading XML message from: {filepath.name}")

    context = XmlContext()
    parser = XmlParser(context=context)

    with open(filepath, 'r') as f:
        xml_content = f.read()

    # Determine type based on content
    if '<joint_status>' in xml_content:
        # Multiple joints
        result = parser.from_string(xml_content, JointStatusesType)
        logger.info(f"  ✓ Parsed JointStatusesType with {len(result.joint_status)} joints")
        for joint in result.joint_status:
            logger.debug(f"    • {joint.name}: {joint.joint_position}")
    else:
        # Single joint
        result = parser.from_string(xml_content, JointStatusType)
        logger.info(f"  ✓ Parsed JointStatusType: {result.name}")
        logger.debug(f"    Position: {result.joint_position}")

    return result

def analyze_messages():
    """Analyze all messages and show statistics"""
    logger.info("=" * 60)
    logger.info("Message Analysis")
    logger.info("=" * 60)

    test_dir = Path("test_messages")

    # Count files
    json_files = list(test_dir.glob("*.json"))
    xml_files = list(test_dir.glob("*.xml"))

    logger.info(f"Found {len(json_files)} JSON files and {len(xml_files)} XML files")

    # Analyze JSON files
    total_joints = 0
    for json_file in json_files:
        with open(json_file, 'r') as f:
            data = json.load(f)

        if isinstance(data, list):
            # Trajectory
            for item in data:
                total_joints += len(item.get('joint_status', []))
        elif 'joint_status' in data:
            # Multiple joints
            total_joints += len(data['joint_status'])
        else:
            # Single joint
            total_joints += 1

    logger.info(f"Total joint measurements across all files: {total_joints}")

def main():
    """Main entry point"""
    logger.info("=" * 60)
    logger.info("🐍 Python CRCL Message Reader")
    logger.info("Reading messages generated by Rust 🦀")
    logger.info("=" * 60)

    test_dir = Path("test_messages")

    if not test_dir.exists():
        logger.error(f"Directory {test_dir} not found!")
        logger.error("Please run the Rust example first:")
        logger.error("  cargo run --example generate_messages")
        return 1

    logger.info(f"Reading from directory: {test_dir}/\n")

    # Read JSON messages
    logger.info("-" * 40)
    logger.info("JSON Messages")
    logger.info("-" * 40)

    # 1. Single joint
    joint1_path = test_dir / "joint_status_1.json"
    if joint1_path.exists():
        joint1 = read_single_joint_json(joint1_path)
        logger.info("")

    # 2. Multiple joints (SCARA)
    scara_path = test_dir / "scara_joints.json"
    if scara_path.exists():
        scara = read_multiple_joints_json(scara_path)
        logger.info("")

    # 3. Trajectory sequence
    traj_path = test_dir / "trajectory_sequence.json"
    if traj_path.exists():
        trajectory = read_trajectory_sequence(traj_path)
        logger.info("")

    # Read XML messages
    logger.info("-" * 40)
    logger.info("XML Messages")
    logger.info("-" * 40)

    for xml_file in test_dir.glob("*.xml"):
        try:
            msg = read_xml_message(xml_file)
            logger.info("")
        except Exception as e:
            logger.warning(f"Could not parse {xml_file.name}: {e}")

    # Analysis
    analyze_messages()

    logger.info("")
    logger.info("✅ Successfully read all Rust-generated messages!")
    logger.info("🔄 Interoperability test: PASSED")

    return 0

if __name__ == "__main__":
    exit(main())