#!/usr/bin/env python3
"""
Test Python CRCL dataclasses with JSON serialization

This demonstrates the Python equivalent of Rust's serde using:
- dataclasses (generated by xsdata)
- JSON serialization via xsdata's built-in support
"""

import json
from dataclasses import asdict
from crcl_python.crclstatus import JointStatusType, JointStatusesType
from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.serializers import JsonSerializer, XmlSerializer
from xsdata.formats.dataclass.parsers import JsonParser, XmlParser

def demo_basic_dataclass():
    """Demo 1: Basic dataclass usage"""
    print("=== 1. Basic Python Dataclass Usage ===\n")

    # Create a joint status
    joint = JointStatusType(
        name="J1_Base_Rotation",
        joint_number=1,
        joint_position=45.5,
        joint_torque_or_force=12.3,
        joint_velocity=15.0
    )

    print(f"Joint created: {joint.name}")
    print(f"  Number: {joint.joint_number}")
    print(f"  Position: {joint.joint_position}°")
    print(f"  Torque: {joint.joint_torque_or_force} Nm")
    print(f"  Velocity: {joint.joint_velocity}°/s")

def demo_json_with_stdlib():
    """Demo 2: JSON using standard library"""
    print("\n=== 2. JSON Serialization (stdlib) ===\n")

    joint = JointStatusType(
        name="J1_Base",
        joint_number=1,
        joint_position=45.5,
        joint_torque_or_force=12.3,
        joint_velocity=15.0
    )

    # Convert to dict and then JSON
    joint_dict = asdict(joint)
    json_str = json.dumps(joint_dict, indent=2)
    print("JSON output:")
    print(json_str)

    # Parse back
    parsed_dict = json.loads(json_str)
    # Note: Need to manually reconstruct the object
    parsed_joint = JointStatusType(**parsed_dict)
    print(f"\nParsed back: {parsed_joint.name} at position {parsed_joint.joint_position}")

def demo_xsdata_serialization():
    """Demo 3: xsdata's built-in serialization (like serde!)"""
    print("\n=== 3. xsdata Serialization (Python's 'serde') ===\n")

    # Create multiple joints
    joints = JointStatusesType(
        name="SCARA_Robot_Status",
        joint_status=[
            JointStatusType(
                name="J1_Base_Rotation",
                joint_number=1,
                joint_position=45.5,
                joint_torque_or_force=12.3,
                joint_velocity=15.0
            ),
            JointStatusType(
                name="J2_Shoulder",
                joint_number=2,
                joint_position=30.25,
                joint_torque_or_force=8.7,
                joint_velocity=10.5
            ),
            JointStatusType(
                name="J3_Z_Axis",
                joint_number=3,
                joint_position=150.0,
                joint_torque_or_force=5.2,
                joint_velocity=25.0
            )
        ]
    )

    context = XmlContext()

    # Serialize to JSON
    json_serializer = JsonSerializer(context=context)
    json_output = json_serializer.render(joints)
    print("xsdata JSON output:")
    print(json_output)

    # Parse JSON back to object
    json_parser = JsonParser(context=context)
    parsed_joints = json_parser.from_string(json_output, JointStatusesType)
    print(f"\nParsed {len(parsed_joints.joint_status)} joints from JSON")

    # Serialize to XML
    print("\n=== XML Output ===")
    xml_serializer = XmlSerializer(context=context)
    xml_output = xml_serializer.render(joints)
    print(xml_output[:500] + "..." if len(xml_output) > 500 else xml_output)

def demo_comparison():
    """Demo 4: Comparison with Rust approach"""
    print("\n=== 4. Python vs Rust Comparison ===\n")

    print("Python (xsdata dataclasses):")
    print("  ✓ Type hints and IDE support")
    print("  ✓ Automatic JSON/XML serialization")
    print("  ✓ Runtime validation")
    print("  ✓ Generated from XSD")
    print("  ~ Performance: Good (pure Python)")
    print("")
    print("Rust (serde):")
    print("  ✓ Compile-time type checking")
    print("  ✓ Zero-copy deserialization")
    print("  ✓ Generated from XSD")
    print("  ✓ Performance: Excellent (native)")
    print("")
    print("Python libraries closest to Rust's serde:")
    print("  1. xsdata - Best for XSD-generated types (used here)")
    print("  2. pydantic - Most popular, great validation")
    print("  3. msgspec - Fastest, uses C extensions")
    print("  4. cattrs - Good for attrs/dataclasses")
    print("  5. mashumaro - Fast dataclass serialization")

if __name__ == "__main__":
    print("=" * 60)
    print("Python CRCL Dataclass Demo")
    print("=" * 60)

    demo_basic_dataclass()
    demo_json_with_stdlib()
    demo_xsdata_serialization()
    demo_comparison()